site_name: Baitian's Blog
site_url: http://127.0.0.1:8000

theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换到深色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到浅色主题

markdown_extensions:
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - admonition
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - attr_list

plugins:
  - search
  - macros
  - mkdocs-simple-hooks:
      hooks:
        on_env: "hooks.hooks:on_env"

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
